# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_two_annotations.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon
from PyQt5.QtCore import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 781)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.video = QtWidgets.QHBoxLayout()
        self.video.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.video.setObjectName("video")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.button_loadvideo = QtWidgets.QPushButton(self.centralwidget)
        self.button_loadvideo.setObjectName("button_loadvideo")
        self.verticalLayout_7.addWidget(self.button_loadvideo)
        self.button_relabel = QtWidgets.QPushButton(self.centralwidget)
        self.button_relabel.setObjectName("button_relabel")
        self.verticalLayout_7.addWidget(self.button_relabel)
        self.button_start = QtWidgets.QPushButton(self.centralwidget)
        self.button_start.setObjectName("button_start")
        self.verticalLayout_7.addWidget(self.button_start)
        self.button_stop = QtWidgets.QPushButton(self.centralwidget)
        self.button_stop.setObjectName("button_stop")
        self.verticalLayout_7.addWidget(self.button_stop)
        self.button_ahead = QtWidgets.QPushButton(self.centralwidget)
        self.button_ahead.setObjectName("button_ahead")
        self.verticalLayout_7.addWidget(self.button_ahead)
        self.button_back = QtWidgets.QPushButton(self.centralwidget)
        self.button_back.setObjectName("button_back")
        self.verticalLayout_7.addWidget(self.button_back)
        self.time_label = QtWidgets.QLabel(self.centralwidget)
        self.time_label.setObjectName("time_label")
        self.verticalLayout_7.addWidget(self.time_label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.time = QtWidgets.QLabel(self.centralwidget)
        self.time.setText("")
        self.time.setObjectName("time")
        self.verticalLayout_7.addWidget(self.time, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.button_save = QtWidgets.QPushButton(self.centralwidget)
        self.button_save.setObjectName("button_save")
        self.verticalLayout_7.addWidget(self.button_save)
        self.button_next = QtWidgets.QPushButton(self.centralwidget)
        self.button_next.setObjectName("button_next")
        self.verticalLayout_7.addWidget(self.button_next)
        self.video.addLayout(self.verticalLayout_7)
        self.video_display = QtWidgets.QVBoxLayout()
        self.video_display.setObjectName("video_display")
        self.display = QtWidgets.QLabel(self.centralwidget)
        self.display.setText("")
        self.display.setObjectName("display")
        self.video_display.addWidget(self.display)
        self.Slider = QtWidgets.QSlider(self.centralwidget)
        self.Slider.setOrientation(QtCore.Qt.Horizontal)
        self.Slider.setObjectName("Slider")
        self.video_display.addWidget(self.Slider)
        self.video.addLayout(self.video_display)
        self.video.setStretch(0, 1)
        self.video.setStretch(1, 10)
        self.verticalLayout.addLayout(self.video)
        self.annotation_global = QtWidgets.QToolBox(self.centralwidget)
        self.annotation_global.setObjectName("annotation_global")
        self.scene = QtWidgets.QWidget()
        self.scene.setGeometry(QtCore.QRect(0, 0, 746, 170))
        self.scene.setObjectName("scene")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.scene)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.scene_box_Layout = QtWidgets.QHBoxLayout()
        self.scene_box_Layout.setObjectName("scene_box_Layout")
        self.scene_box_Label = QtWidgets.QLabel(self.scene)
        self.scene_box_Label.setObjectName("scene_box_Label")
        self.scene_box_Layout.addWidget(self.scene_box_Label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.scene_box = QtWidgets.QComboBox(self.scene)
        self.scene_box.setObjectName("scene_box")
        self.scene_box_Layout.addWidget(self.scene_box)
        self.scene_box_Layout.setStretch(0, 1)
        self.scene_box_Layout.setStretch(1, 5)
        self.verticalLayout_27.addLayout(self.scene_box_Layout)
        self.scene_input_Layout = QtWidgets.QHBoxLayout()
        self.scene_input_Layout.setObjectName("scene_input_Layout")
        self.scene_input_Label = QtWidgets.QLabel(self.scene)
        self.scene_input_Label.setObjectName("scene_input_Label")
        self.scene_input_Layout.addWidget(self.scene_input_Label)
        self.scene_input = QtWidgets.QLineEdit(self.scene)
        self.scene_input.setObjectName("scene_input")
        self.scene_input_Layout.addWidget(self.scene_input)
        self.scene_input_Layout.setStretch(1, 5)
        self.verticalLayout_27.addLayout(self.scene_input_Layout)
        self.scene_display = QtWidgets.QLabel(self.scene)
        self.scene_display.setObjectName("scene_display")
        self.verticalLayout_27.addWidget(self.scene_display)
        self.scene_display.raise_()
        self.annotation_global.addItem(self.scene, "")
        self.event = QtWidgets.QWidget()
        self.event.setGeometry(QtCore.QRect(0, 0, 746, 170))
        self.event.setObjectName("event")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.event)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.evnet_box_Layout = QtWidgets.QHBoxLayout()
        self.evnet_box_Layout.setObjectName("evnet_box_Layout")
        self.event_box_Label = QtWidgets.QLabel(self.event)
        self.event_box_Label.setObjectName("event_box_Label")
        self.evnet_box_Layout.addWidget(self.event_box_Label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.event_box = QtWidgets.QComboBox(self.event)
        self.event_box.setObjectName("event_box")
        self.evnet_box_Layout.addWidget(self.event_box)
        self.evnet_box_Layout.setStretch(0, 1)
        self.evnet_box_Layout.setStretch(1, 3)
        self.verticalLayout_28.addLayout(self.evnet_box_Layout)
        self.event_input_Layout = QtWidgets.QHBoxLayout()
        self.event_input_Layout.setObjectName("event_input_Layout")
        self.event_input_Label = QtWidgets.QLabel(self.event)
        self.event_input_Label.setObjectName("event_input_Label")
        self.event_input_Layout.addWidget(self.event_input_Label)
        self.event_input = QtWidgets.QLineEdit(self.event)
        self.event_input.setObjectName("event_input")
        self.event_input_Layout.addWidget(self.event_input)
        self.event_input_Layout.setStretch(1, 5)
        self.verticalLayout_28.addLayout(self.event_input_Layout)
        self.annotation_global.addItem(self.event, "")
        self.story = QtWidgets.QWidget()
        self.story.setGeometry(QtCore.QRect(0, 0, 746, 246))
        self.story.setObjectName("story")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.story)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.story_reference_Label = QtWidgets.QLabel(self.story)
        self.story_reference_Label.setObjectName("story_reference_Label")
        self.verticalLayout_29.addWidget(self.story_reference_Label)
        self.story_reference = QtWidgets.QPlainTextEdit(self.story)
        self.story_reference.setObjectName("story_reference")
        self.verticalLayout_29.addWidget(self.story_reference)
        self.story_input_Label = QtWidgets.QLabel(self.story)
        self.story_input_Label.setObjectName("story_input_Label")
        self.verticalLayout_29.addWidget(self.story_input_Label)
        self.story_input = QtWidgets.QPlainTextEdit(self.story)
        self.story_input.setObjectName("story_input")
        self.verticalLayout_29.addWidget(self.story_input)
        self.annotation_global.addItem(self.story, "")
        self.verticalLayout.addWidget(self.annotation_global)
        self.verticalLayout.setStretch(0, 3)
        self.verticalLayout.setStretch(1, 2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayoutlogo = QtWidgets.QVBoxLayout()
        self.verticalLayoutlogo.setObjectName("verticalLayoutlogo")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setText("")
        self.logo.setObjectName("logo")
        self.verticalLayoutlogo.addWidget(self.logo)
        self.annotation = QtWidgets.QToolBox(self.centralwidget)
        self.annotation.setObjectName("annotation")
        self.characters = QtWidgets.QWidget()
        self.characters.setGeometry(QtCore.QRect(0, 0, 496, 378))
        self.characters.setObjectName("characters")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.characters)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.name_input_Layout = QtWidgets.QHBoxLayout()
        self.name_input_Layout.setObjectName("name_input_Layout")
        self.name_input_Label = QtWidgets.QLabel(self.characters)
        self.name_input_Label.setObjectName("name_input_Label")
        self.name_input_Layout.addWidget(self.name_input_Label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.name_input = QtWidgets.QComboBox(self.characters)
        self.name_input.setObjectName("name_input")
        self.name_input_Layout.addWidget(self.name_input)
        self.name_input_Layout.setStretch(0, 1)
        self.name_input_Layout.setStretch(1, 5)
        self.verticalLayout_13.addLayout(self.name_input_Layout)
        self.attibute_Layout = QtWidgets.QHBoxLayout()
        self.attibute_Layout.setObjectName("attibute_Layout")
        self.sex_Label = QtWidgets.QLabel(self.characters)
        self.sex_Label.setObjectName("sex_Label")
        self.attibute_Layout.addWidget(self.sex_Label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.sex_box = QtWidgets.QComboBox(self.characters)
        self.sex_box.setObjectName("sex_box")
        self.attibute_Layout.addWidget(self.sex_box)
        self.age_Label = QtWidgets.QLabel(self.characters)
        self.age_Label.setObjectName("age_Label")
        self.attibute_Layout.addWidget(self.age_Label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.age_box = QtWidgets.QComboBox(self.characters)
        self.age_box.setObjectName("age_box")
        self.attibute_Layout.addWidget(self.age_box)
        self.verticalLayout_13.addLayout(self.attibute_Layout)
        self.characters_save_Layout = QtWidgets.QHBoxLayout()
        self.characters_save_Layout.setObjectName("characters_save_Layout")
        self.characters_save = QtWidgets.QPushButton(self.characters)
        self.characters_save.setObjectName("characters_save")
        self.characters_save_Layout.addWidget(self.characters_save)
        spacerItem = QtWidgets.QSpacerItem(28, 18, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.characters_save_Layout.addItem(spacerItem)
        self.characters_save_Layout.setStretch(0, 2)
        self.characters_save_Layout.setStretch(1, 5)
        self.verticalLayout_13.addLayout(self.characters_save_Layout)
        self.characters_box_Layout = QtWidgets.QHBoxLayout()
        self.characters_box_Layout.setObjectName("characters_box_Layout")
        self.characters_box_Label = QtWidgets.QLabel(self.characters)
        self.characters_box_Label.setObjectName("characters_box_Label")
        self.characters_box_Layout.addWidget(self.characters_box_Label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.characters_box = QtWidgets.QComboBox(self.characters)
        self.characters_box.setObjectName("characters_box")
        self.characters_box_Layout.addWidget(self.characters_box)
        self.characters_box_Layout.setStretch(0, 1)
        self.characters_box_Layout.setStretch(1, 5)
        self.verticalLayout_13.addLayout(self.characters_box_Layout)
        self.characters_delete_Layout = QtWidgets.QHBoxLayout()
        self.characters_delete_Layout.setObjectName("characters_delete_Layout")
        self.characters_delete = QtWidgets.QPushButton(self.characters)
        self.characters_delete.setObjectName("characters_delete")
        self.characters_delete_Layout.addWidget(self.characters_delete)
        spacerItem1 = QtWidgets.QSpacerItem(28, 18, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.characters_delete_Layout.addItem(spacerItem1)
        self.characters_delete_Layout.setStretch(0, 2)
        self.characters_delete_Layout.setStretch(1, 5)
        self.verticalLayout_13.addLayout(self.characters_delete_Layout)
        self.annotation.addItem(self.characters, "")
        self.actions = QtWidgets.QWidget()
        self.actions.setGeometry(QtCore.QRect(0, 0, 496, 378))
        self.actions.setObjectName("actions")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.actions)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.actions_box_Layout = QtWidgets.QHBoxLayout()
        self.actions_box_Layout.setObjectName("actions_box_Layout")
        self.actions_box_Label = QtWidgets.QLabel(self.actions)
        self.actions_box_Label.setObjectName("actions_box_Label")
        self.actions_box_Layout.addWidget(self.actions_box_Label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.actions_box = QtWidgets.QComboBox(self.actions)
        self.actions_box.setObjectName("actions_box")
        self.actions_box_Layout.addWidget(self.actions_box)
        self.action_input_Label = QtWidgets.QLabel(self.actions)
        self.action_input_Label.setObjectName("action_input_Label")
        self.actions_box_Layout.addWidget(self.action_input_Label, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.action_input = QtWidgets.QLineEdit(self.actions)
        self.action_input.setObjectName("action_input")
        self.actions_box_Layout.addWidget(self.action_input)
        self.actions_box_Layout.setStretch(0, 1)
        self.actions_box_Layout.setStretch(1, 3)
        self.actions_box_Layout.setStretch(2, 1)
        self.actions_box_Layout.setStretch(3, 3)
        self.verticalLayout_6.addLayout(self.actions_box_Layout)
        self.actions_human_Layout = QtWidgets.QHBoxLayout()
        self.actions_human_Layout.setObjectName("actions_human_Layout")
        self.actions_human_box_Label = QtWidgets.QLabel(self.actions)
        self.actions_human_box_Label.setObjectName("actions_human_box_Label")
        self.actions_human_Layout.addWidget(self.actions_human_box_Label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.actions_human_box = QtWidgets.QComboBox(self.actions)
        self.actions_human_box.setObjectName("actions_human_box")
        self.actions_human_Layout.addWidget(self.actions_human_box)
        self.actions_human_Layout.setStretch(0, 1)
        self.actions_human_Layout.setStretch(1, 5)
        self.verticalLayout_6.addLayout(self.actions_human_Layout)
        self.actions_times = QtWidgets.QHBoxLayout()
        self.actions_times.setObjectName("actions_times")
        self.time_start_actions_Label = QtWidgets.QLabel(self.actions)
        self.time_start_actions_Label.setObjectName("time_start_actions_Label")
        self.actions_times.addWidget(self.time_start_actions_Label)
        self.time_start_actions_input = QtWidgets.QLineEdit(self.actions)
        self.time_start_actions_input.setObjectName("time_start_actions_input")
        self.actions_times.addWidget(self.time_start_actions_input)
        self.time_end_actions_Label = QtWidgets.QLabel(self.actions)
        self.time_end_actions_Label.setObjectName("time_end_actions_Label")
        self.actions_times.addWidget(self.time_end_actions_Label)
        self.time_end_actions_input = QtWidgets.QLineEdit(self.actions)
        self.time_end_actions_input.setObjectName("time_end_actions_input")
        self.actions_times.addWidget(self.time_end_actions_input)
        self.verticalLayout_6.addLayout(self.actions_times)
        self.actions_save_Layout = QtWidgets.QHBoxLayout()
        self.actions_save_Layout.setObjectName("actions_save_Layout")
        self.actions_save = QtWidgets.QPushButton(self.actions)
        self.actions_save.setObjectName("actions_save")
        self.actions_save_Layout.addWidget(self.actions_save)
        spacerItem2 = QtWidgets.QSpacerItem(28, 18, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.actions_save_Layout.addItem(spacerItem2)
        self.actions_save_Layout.setStretch(0, 2)
        self.actions_save_Layout.setStretch(1, 5)
        self.verticalLayout_6.addLayout(self.actions_save_Layout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.actions_list_human_Label = QtWidgets.QLabel(self.actions)
        self.actions_list_human_Label.setObjectName("actions_list_human_Label")
        self.horizontalLayout_2.addWidget(self.actions_list_human_Label)
        self.actions_list_human_box = QtWidgets.QComboBox(self.actions)
        self.actions_list_human_box.setObjectName("actions_list_human_box")
        self.horizontalLayout_2.addWidget(self.actions_list_human_box)
        self.actions_list_Label = QtWidgets.QLabel(self.actions)
        self.actions_list_Label.setObjectName("actions_list_Label")
        self.horizontalLayout_2.addWidget(self.actions_list_Label)
        self.actions_list = QtWidgets.QComboBox(self.actions)
        self.actions_list.setObjectName("actions_list")
        self.horizontalLayout_2.addWidget(self.actions_list)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 2)
        self.horizontalLayout_2.setStretch(2, 1)
        self.horizontalLayout_2.setStretch(3, 2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.actions_delete_Layout = QtWidgets.QHBoxLayout()
        self.actions_delete_Layout.setObjectName("actions_delete_Layout")
        self.actions_delete = QtWidgets.QPushButton(self.actions)
        self.actions_delete.setObjectName("actions_delete")
        self.actions_delete_Layout.addWidget(self.actions_delete)
        spacerItem3 = QtWidgets.QSpacerItem(28, 18, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.actions_delete_Layout.addItem(spacerItem3)
        self.actions_delete_Layout.setStretch(0, 2)
        self.actions_delete_Layout.setStretch(1, 5)
        self.verticalLayout_6.addLayout(self.actions_delete_Layout)
        self.annotation.addItem(self.actions, "")
        self.expressions = QtWidgets.QWidget()
        self.expressions.setGeometry(QtCore.QRect(0, 0, 496, 378))
        self.expressions.setObjectName("expressions")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.expressions)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.expressions_box_Layout = QtWidgets.QHBoxLayout()
        self.expressions_box_Layout.setObjectName("expressions_box_Layout")
        self.expressions_box_Label = QtWidgets.QLabel(self.expressions)
        self.expressions_box_Label.setObjectName("expressions_box_Label")
        self.expressions_box_Layout.addWidget(self.expressions_box_Label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.expressions_box = QtWidgets.QComboBox(self.expressions)
        self.expressions_box.setObjectName("expressions_box")
        self.expressions_box_Layout.addWidget(self.expressions_box)
        self.expression_input_Label = QtWidgets.QLabel(self.expressions)
        self.expression_input_Label.setObjectName("expression_input_Label")
        self.expressions_box_Layout.addWidget(self.expression_input_Label)
        self.expression_input = QtWidgets.QLineEdit(self.expressions)
        self.expression_input.setObjectName("expression_input")
        self.expressions_box_Layout.addWidget(self.expression_input)
        self.expressions_box_Layout.setStretch(0, 1)
        self.expressions_box_Layout.setStretch(1, 3)
        self.expressions_box_Layout.setStretch(2, 1)
        self.expressions_box_Layout.setStretch(3, 3)
        self.verticalLayout_5.addLayout(self.expressions_box_Layout)
        self.expressions_human_Layout = QtWidgets.QHBoxLayout()
        self.expressions_human_Layout.setObjectName("expressions_human_Layout")
        self.expressions_human_box_Label = QtWidgets.QLabel(self.expressions)
        self.expressions_human_box_Label.setObjectName("expressions_human_box_Label")
        self.expressions_human_Layout.addWidget(self.expressions_human_box_Label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.expressions_human_box = QtWidgets.QComboBox(self.expressions)
        self.expressions_human_box.setObjectName("expressions_human_box")
        self.expressions_human_Layout.addWidget(self.expressions_human_box)
        self.expressions_human_Layout.setStretch(0, 1)
        self.expressions_human_Layout.setStretch(1, 5)
        self.verticalLayout_5.addLayout(self.expressions_human_Layout)
        self.expressions_times = QtWidgets.QHBoxLayout()
        self.expressions_times.setObjectName("expressions_times")
        self.time_start_expressions_Label = QtWidgets.QLabel(self.expressions)
        self.time_start_expressions_Label.setObjectName("time_start_expressions_Label")
        self.expressions_times.addWidget(self.time_start_expressions_Label)
        self.time_start_expressions_input = QtWidgets.QLineEdit(self.expressions)
        self.time_start_expressions_input.setObjectName("time_start_expressions_input")
        self.expressions_times.addWidget(self.time_start_expressions_input)
        self.time_end_expressions_Label = QtWidgets.QLabel(self.expressions)
        self.time_end_expressions_Label.setObjectName("time_end_expressions_Label")
        self.expressions_times.addWidget(self.time_end_expressions_Label)
        self.time_end_expressions_input = QtWidgets.QLineEdit(self.expressions)
        self.time_end_expressions_input.setObjectName("time_end_expressions_input")
        self.expressions_times.addWidget(self.time_end_expressions_input)
        self.verticalLayout_5.addLayout(self.expressions_times)
        self.expressions_save_Layout = QtWidgets.QHBoxLayout()
        self.expressions_save_Layout.setObjectName("expressions_save_Layout")
        self.expressions_save = QtWidgets.QPushButton(self.expressions)
        self.expressions_save.setObjectName("expressions_save")
        self.expressions_save_Layout.addWidget(self.expressions_save)
        spacerItem4 = QtWidgets.QSpacerItem(28, 18, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.expressions_save_Layout.addItem(spacerItem4)
        self.expressions_save_Layout.setStretch(0, 2)
        self.expressions_save_Layout.setStretch(1, 5)
        self.verticalLayout_5.addLayout(self.expressions_save_Layout)
        self.expressions_list_Layout = QtWidgets.QHBoxLayout()
        self.expressions_list_Layout.setObjectName("expressions_list_Layout")
        self.actions_list_human_Label_2 = QtWidgets.QLabel(self.expressions)
        self.actions_list_human_Label_2.setObjectName("actions_list_human_Label_2")
        self.expressions_list_Layout.addWidget(self.actions_list_human_Label_2)
        self.expressions_list_human_box = QtWidgets.QComboBox(self.expressions)
        self.expressions_list_human_box.setObjectName("expressions_list_human_box")
        self.expressions_list_Layout.addWidget(self.expressions_list_human_box)
        self.expressions_list_Label = QtWidgets.QLabel(self.expressions)
        self.expressions_list_Label.setObjectName("expressions_list_Label")
        self.expressions_list_Layout.addWidget(self.expressions_list_Label)
        self.expressions_list = QtWidgets.QComboBox(self.expressions)
        self.expressions_list.setObjectName("expressions_list")
        self.expressions_list_Layout.addWidget(self.expressions_list)
        self.expressions_list_Layout.setStretch(0, 1)
        self.expressions_list_Layout.setStretch(1, 2)
        self.expressions_list_Layout.setStretch(2, 1)
        self.expressions_list_Layout.setStretch(3, 2)
        self.verticalLayout_5.addLayout(self.expressions_list_Layout)
        self.expressions_delete_Layout = QtWidgets.QHBoxLayout()
        self.expressions_delete_Layout.setObjectName("expressions_delete_Layout")
        self.expressions_delete = QtWidgets.QPushButton(self.expressions)
        self.expressions_delete.setObjectName("expressions_delete")
        self.expressions_delete_Layout.addWidget(self.expressions_delete)
        spacerItem5 = QtWidgets.QSpacerItem(28, 18, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.expressions_delete_Layout.addItem(spacerItem5)
        self.expressions_delete_Layout.setStretch(0, 2)
        self.expressions_delete_Layout.setStretch(1, 5)
        self.verticalLayout_5.addLayout(self.expressions_delete_Layout)
        self.annotation.addItem(self.expressions, "")
        self.relation_HH = QtWidgets.QWidget()
        self.relation_HH.setGeometry(QtCore.QRect(0, 0, 496, 378))
        self.relation_HH.setObjectName("relation_HH")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.relation_HH)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.human12 = QtWidgets.QHBoxLayout()
        self.human12.setObjectName("human12")
        self.human1_box_Layout = QtWidgets.QHBoxLayout()
        self.human1_box_Layout.setObjectName("human1_box_Layout")
        self.human1_box_Label = QtWidgets.QLabel(self.relation_HH)
        self.human1_box_Label.setObjectName("human1_box_Label")
        self.human1_box_Layout.addWidget(self.human1_box_Label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.human1_box = QtWidgets.QComboBox(self.relation_HH)
        self.human1_box.setObjectName("human1_box")
        self.human1_box_Layout.addWidget(self.human1_box)
        self.human1_box_Layout.setStretch(0, 1)
        self.human1_box_Layout.setStretch(1, 5)
        self.human12.addLayout(self.human1_box_Layout)
        self.human2_box_Layout = QtWidgets.QHBoxLayout()
        self.human2_box_Layout.setObjectName("human2_box_Layout")
        self.human2_box_Label = QtWidgets.QLabel(self.relation_HH)
        self.human2_box_Label.setObjectName("human2_box_Label")
        self.human2_box_Layout.addWidget(self.human2_box_Label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.human2_box = QtWidgets.QComboBox(self.relation_HH)
        self.human2_box.setObjectName("human2_box")
        self.human2_box_Layout.addWidget(self.human2_box)
        self.human2_box_Layout.setStretch(0, 1)
        self.human2_box_Layout.setStretch(1, 5)
        self.human12.addLayout(self.human2_box_Layout)
        self.verticalLayout_3.addLayout(self.human12)
        self.relation_HH_input_Layout_2 = QtWidgets.QHBoxLayout()
        self.relation_HH_input_Layout_2.setObjectName("relation_HH_input_Layout_2")
        self.relation_HH_box_Layout = QtWidgets.QHBoxLayout()
        self.relation_HH_box_Layout.setObjectName("relation_HH_box_Layout")
        self.relation_HH_box_Label = QtWidgets.QLabel(self.relation_HH)
        self.relation_HH_box_Label.setObjectName("relation_HH_box_Label")
        self.relation_HH_box_Layout.addWidget(self.relation_HH_box_Label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.relation_HH_box = QtWidgets.QComboBox(self.relation_HH)
        self.relation_HH_box.setObjectName("relation_HH_box")
        self.relation_HH_box_Layout.addWidget(self.relation_HH_box)
        self.relation_HH_box_Layout.setStretch(0, 1)
        self.relation_HH_box_Layout.setStretch(1, 5)
        self.relation_HH_input_Layout_2.addLayout(self.relation_HH_box_Layout)
        self.relation_HH_input_Layout = QtWidgets.QHBoxLayout()
        self.relation_HH_input_Layout.setObjectName("relation_HH_input_Layout")
        self.relation_HH_input_Label = QtWidgets.QLabel(self.relation_HH)
        self.relation_HH_input_Label.setObjectName("relation_HH_input_Label")
        self.relation_HH_input_Layout.addWidget(self.relation_HH_input_Label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.relation_HH_input = QtWidgets.QLineEdit(self.relation_HH)
        self.relation_HH_input.setObjectName("relation_HH_input")
        self.relation_HH_input_Layout.addWidget(self.relation_HH_input)
        self.relation_HH_input_Layout.setStretch(0, 1)
        self.relation_HH_input_Layout.setStretch(1, 5)
        self.relation_HH_input_Layout_2.addLayout(self.relation_HH_input_Layout)
        self.verticalLayout_3.addLayout(self.relation_HH_input_Layout_2)
        self.relation_HH_save_Layout = QtWidgets.QHBoxLayout()
        self.relation_HH_save_Layout.setObjectName("relation_HH_save_Layout")
        self.relation_HH_save = QtWidgets.QPushButton(self.relation_HH)
        self.relation_HH_save.setObjectName("relation_HH_save")
        self.relation_HH_save_Layout.addWidget(self.relation_HH_save)
        spacerItem6 = QtWidgets.QSpacerItem(28, 18, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.relation_HH_save_Layout.addItem(spacerItem6)
        self.relation_HH_save_Layout.setStretch(0, 2)
        self.relation_HH_save_Layout.setStretch(1, 5)
        self.verticalLayout_3.addLayout(self.relation_HH_save_Layout)
        self.relation_HH_list_Layout = QtWidgets.QHBoxLayout()
        self.relation_HH_list_Layout.setObjectName("relation_HH_list_Layout")
        self.relation_HH_list_Label = QtWidgets.QLabel(self.relation_HH)
        self.relation_HH_list_Label.setObjectName("relation_HH_list_Label")
        self.relation_HH_list_Layout.addWidget(self.relation_HH_list_Label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.relation_HH_list = QtWidgets.QComboBox(self.relation_HH)
        self.relation_HH_list.setObjectName("relation_HH_list")
        self.relation_HH_list_Layout.addWidget(self.relation_HH_list)
        self.relation_HH_list_Layout.setStretch(0, 1)
        self.relation_HH_list_Layout.setStretch(1, 5)
        self.verticalLayout_3.addLayout(self.relation_HH_list_Layout)
        self.relation_HH_delete_Layout = QtWidgets.QHBoxLayout()
        self.relation_HH_delete_Layout.setObjectName("relation_HH_delete_Layout")
        self.relation_HH_delete = QtWidgets.QPushButton(self.relation_HH)
        self.relation_HH_delete.setObjectName("relation_HH_delete")
        self.relation_HH_delete_Layout.addWidget(self.relation_HH_delete)
        spacerItem7 = QtWidgets.QSpacerItem(28, 18, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.relation_HH_delete_Layout.addItem(spacerItem7)
        self.relation_HH_delete_Layout.setStretch(0, 2)
        self.relation_HH_delete_Layout.setStretch(1, 5)
        self.verticalLayout_3.addLayout(self.relation_HH_delete_Layout)
        self.annotation.addItem(self.relation_HH, "")
        self.interaction = QtWidgets.QWidget()
        self.interaction.setGeometry(QtCore.QRect(0, 0, 496, 378))
        self.interaction.setObjectName("interaction")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.interaction)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.human34 = QtWidgets.QHBoxLayout()
        self.human34.setObjectName("human34")
        self.human3_box_Layout = QtWidgets.QHBoxLayout()
        self.human3_box_Layout.setObjectName("human3_box_Layout")
        self.human3_box_Label = QtWidgets.QLabel(self.interaction)
        self.human3_box_Label.setObjectName("human3_box_Label")
        self.human3_box_Layout.addWidget(self.human3_box_Label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.human3_box = QtWidgets.QComboBox(self.interaction)
        self.human3_box.setObjectName("human3_box")
        self.human3_box_Layout.addWidget(self.human3_box)
        self.human3_box_Layout.setStretch(0, 1)
        self.human3_box_Layout.setStretch(1, 5)
        self.human34.addLayout(self.human3_box_Layout)
        self.human4_box_Layout = QtWidgets.QHBoxLayout()
        self.human4_box_Layout.setObjectName("human4_box_Layout")
        self.human4_box_Label = QtWidgets.QLabel(self.interaction)
        self.human4_box_Label.setObjectName("human4_box_Label")
        self.human4_box_Layout.addWidget(self.human4_box_Label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.human4_box = QtWidgets.QComboBox(self.interaction)
        self.human4_box.setObjectName("human4_box")
        self.human4_box_Layout.addWidget(self.human4_box)
        self.human4_box_Layout.setStretch(0, 1)
        self.human4_box_Layout.setStretch(1, 5)
        self.human34.addLayout(self.human4_box_Layout)
        self.verticalLayout_2.addLayout(self.human34)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.interaction_box_Layout = QtWidgets.QHBoxLayout()
        self.interaction_box_Layout.setObjectName("interaction_box_Layout")
        self.interaction_box_Label = QtWidgets.QLabel(self.interaction)
        self.interaction_box_Label.setObjectName("interaction_box_Label")
        self.interaction_box_Layout.addWidget(self.interaction_box_Label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.interaction_box = QtWidgets.QComboBox(self.interaction)
        self.interaction_box.setObjectName("interaction_box")
        self.interaction_box_Layout.addWidget(self.interaction_box)
        self.interaction_box_Layout.setStretch(0, 1)
        self.interaction_box_Layout.setStretch(1, 5)
        self.horizontalLayout_7.addLayout(self.interaction_box_Layout)
        self.interaction_input_Layout = QtWidgets.QHBoxLayout()
        self.interaction_input_Layout.setObjectName("interaction_input_Layout")
        self.interaction_input_Label = QtWidgets.QLabel(self.interaction)
        self.interaction_input_Label.setObjectName("interaction_input_Label")
        self.interaction_input_Layout.addWidget(self.interaction_input_Label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.interaction_input = QtWidgets.QLineEdit(self.interaction)
        self.interaction_input.setObjectName("interaction_input")
        self.interaction_input_Layout.addWidget(self.interaction_input)
        self.interaction_input_Layout.setStretch(0, 1)
        self.interaction_input_Layout.setStretch(1, 5)
        self.horizontalLayout_7.addLayout(self.interaction_input_Layout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.reason_input_Layout = QtWidgets.QHBoxLayout()
        self.reason_input_Layout.setObjectName("reason_input_Layout")
        self.reason_input_Label = QtWidgets.QLabel(self.interaction)
        self.reason_input_Label.setObjectName("reason_input_Label")
        self.reason_input_Layout.addWidget(self.reason_input_Label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.reason_input = QtWidgets.QLineEdit(self.interaction)
        self.reason_input.setObjectName("reason_input")
        self.reason_input_Layout.addWidget(self.reason_input)
        self.reason_input_Layout.setStretch(0, 1)
        self.reason_input_Layout.setStretch(1, 5)
        self.verticalLayout_2.addLayout(self.reason_input_Layout)
        self.interaction_times = QtWidgets.QHBoxLayout()
        self.interaction_times.setObjectName("interaction_times")
        self.time_start_interaction_Label = QtWidgets.QLabel(self.interaction)
        self.time_start_interaction_Label.setObjectName("time_start_interaction_Label")
        self.interaction_times.addWidget(self.time_start_interaction_Label)
        self.time_start_interaction_input = QtWidgets.QLineEdit(self.interaction)
        self.time_start_interaction_input.setObjectName("time_start_interaction_input")
        self.interaction_times.addWidget(self.time_start_interaction_input)
        self.time_end_interaction_Label = QtWidgets.QLabel(self.interaction)
        self.time_end_interaction_Label.setObjectName("time_end_interaction_Label")
        self.interaction_times.addWidget(self.time_end_interaction_Label)
        self.time_end_interaction_input = QtWidgets.QLineEdit(self.interaction)
        self.time_end_interaction_input.setObjectName("time_end_interaction_input")
        self.interaction_times.addWidget(self.time_end_interaction_input)
        self.verticalLayout_2.addLayout(self.interaction_times)
        self.interaction_save_Layout = QtWidgets.QHBoxLayout()
        self.interaction_save_Layout.setObjectName("interaction_save_Layout")
        self.interaction_save = QtWidgets.QPushButton(self.interaction)
        self.interaction_save.setObjectName("interaction_save")
        self.interaction_save_Layout.addWidget(self.interaction_save)
        spacerItem8 = QtWidgets.QSpacerItem(28, 18, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.interaction_save_Layout.addItem(spacerItem8)
        self.interaction_save_Layout.setStretch(0, 2)
        self.interaction_save_Layout.setStretch(1, 5)
        self.verticalLayout_2.addLayout(self.interaction_save_Layout)
        self.interaction_list_Layout = QtWidgets.QHBoxLayout()
        self.interaction_list_Layout.setObjectName("interaction_list_Layout")
        self.interaction_list_Label = QtWidgets.QLabel(self.interaction)
        self.interaction_list_Label.setObjectName("interaction_list_Label")
        self.interaction_list_Layout.addWidget(self.interaction_list_Label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.interaction_list = QtWidgets.QComboBox(self.interaction)
        self.interaction_list.setObjectName("interaction_list")
        self.interaction_list_Layout.addWidget(self.interaction_list)
        self.interaction_list_Layout.setStretch(0, 1)
        self.interaction_list_Layout.setStretch(1, 5)
        self.verticalLayout_2.addLayout(self.interaction_list_Layout)
        self.interaction_delete_Layout = QtWidgets.QHBoxLayout()
        self.interaction_delete_Layout.setObjectName("interaction_delete_Layout")
        self.interaction_delete = QtWidgets.QPushButton(self.interaction)
        self.interaction_delete.setObjectName("interaction_delete")
        self.interaction_delete_Layout.addWidget(self.interaction_delete)
        spacerItem9 = QtWidgets.QSpacerItem(28, 18, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.interaction_delete_Layout.addItem(spacerItem9)
        self.interaction_delete_Layout.setStretch(0, 2)
        self.interaction_delete_Layout.setStretch(1, 5)
        self.verticalLayout_2.addLayout(self.interaction_delete_Layout)
        self.annotation.addItem(self.interaction, "")
        self.verticalLayoutlogo.addWidget(self.annotation)
        self.verticalLayoutlogo.setStretch(0, 1)
        self.verticalLayoutlogo.setStretch(1, 3)
        self.horizontalLayout.addLayout(self.verticalLayoutlogo)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.annotation_global.setCurrentIndex(0)
        self.annotation.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        MainWindow.setStyleSheet("#MainWindow{border-image:url(./pic/background.jpg);}")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_loadvideo.setText(_translate("MainWindow", "导入"))
        self.button_relabel.setText(_translate("MainWindow", "校正"))
        self.button_start.setText(_translate("MainWindow", "播放"))
        self.button_stop.setText(_translate("MainWindow", "暂停"))
        self.button_ahead.setText(_translate("MainWindow", "快进"))
        self.button_back.setText(_translate("MainWindow", "快退"))
        self.time_label.setText(_translate("MainWindow", "时间（帧）"))
        self.button_save.setText(_translate("MainWindow", "保存标注"))
        self.button_next.setText(_translate("MainWindow", "下一个视频"))
        self.scene_box_Label.setText(_translate("MainWindow", "场景选择"))
        self.scene_input_Label.setText(_translate("MainWindow", "场景输入"))
        self.scene_display.setText(_translate("MainWindow", "场景显示"))
        self.annotation_global.setItemText(self.annotation_global.indexOf(self.scene), _translate("MainWindow", "TopK场景类别"))
        self.event_box_Label.setText(_translate("MainWindow", "事件类别选择"))
        self.event_input_Label.setText(_translate("MainWindow", "事件输入"))
        self.annotation_global.setItemText(self.annotation_global.indexOf(self.event), _translate("MainWindow", "事件类别"))
        self.story_reference_Label.setText(_translate("MainWindow", "参考剧情"))
        self.story_input_Label.setText(_translate("MainWindow", "剧情描述输入"))
        self.annotation_global.setItemText(self.annotation_global.indexOf(self.story), _translate("MainWindow", "剧情描述"))
        self.name_input_Label.setText(_translate("MainWindow", "角色名"))
        self.sex_Label.setText(_translate("MainWindow", "性别"))
        self.age_Label.setText(_translate("MainWindow", "年龄段"))
        self.characters_save.setText(_translate("MainWindow", "添加"))
        self.characters_box_Label.setText(_translate("MainWindow", "已有角色"))
        self.characters_delete.setText(_translate("MainWindow", "删除"))
        self.annotation.setItemText(self.annotation.indexOf(self.characters), _translate("MainWindow", "角色"))
        self.actions_box_Label.setText(_translate("MainWindow", "动作类别"))
        self.action_input_Label.setText(_translate("MainWindow", "其它"))
        self.actions_human_box_Label.setText(_translate("MainWindow", "动作所属"))
        self.time_start_actions_Label.setText(_translate("MainWindow", "动作时间：起始帧"))
        self.time_end_actions_Label.setText(_translate("MainWindow", "结束帧"))
        self.actions_save.setText(_translate("MainWindow", "添加"))
        self.actions_list_human_Label.setText(_translate("MainWindow", "选择角色"))
        self.actions_list_Label.setText(_translate("MainWindow", "已有动作"))
        self.actions_delete.setText(_translate("MainWindow", "删除"))
        self.annotation.setItemText(self.annotation.indexOf(self.actions), _translate("MainWindow", "动作类别"))
        self.expressions_box_Label.setText(_translate("MainWindow", "表情类别"))
        self.expression_input_Label.setText(_translate("MainWindow", "其它"))
        self.expressions_human_box_Label.setText(_translate("MainWindow", "表情所属"))
        self.time_start_expressions_Label.setText(_translate("MainWindow", "表情时间：起始帧"))
        self.time_end_expressions_Label.setText(_translate("MainWindow", "结束帧"))
        self.expressions_save.setText(_translate("MainWindow", "添加"))
        self.actions_list_human_Label_2.setText(_translate("MainWindow", "选择角色"))
        self.expressions_list_Label.setText(_translate("MainWindow", "已有表情"))
        self.expressions_delete.setText(_translate("MainWindow", "删除"))
        self.annotation.setItemText(self.annotation.indexOf(self.expressions), _translate("MainWindow", "表情类别"))
        self.human1_box_Label.setText(_translate("MainWindow", "角色1"))
        self.human2_box_Label.setText(_translate("MainWindow", "角色2"))
        self.relation_HH_box_Label.setText(_translate("MainWindow", "关系"))
        self.relation_HH_input_Label.setText(_translate("MainWindow", "其它"))
        self.relation_HH_save.setText(_translate("MainWindow", "添加"))
        self.relation_HH_list_Label.setText(_translate("MainWindow", "已有关系"))
        self.relation_HH_delete.setText(_translate("MainWindow", "删除"))
        self.annotation.setItemText(self.annotation.indexOf(self.relation_HH), _translate("MainWindow", "人人关系"))
        self.human3_box_Label.setText(_translate("MainWindow", "角色1"))
        self.human4_box_Label.setText(_translate("MainWindow", "角色2"))
        self.interaction_box_Label.setText(_translate("MainWindow", "交互类型"))
        self.interaction_input_Label.setText(_translate("MainWindow", "其它"))
        self.reason_input_Label.setText(_translate("MainWindow", "交互原因"))
        self.time_start_interaction_Label.setText(_translate("MainWindow", "交互时间：起始帧"))
        self.time_end_interaction_Label.setText(_translate("MainWindow", "结束帧"))
        self.interaction_save.setText(_translate("MainWindow", "添加"))
        self.interaction_list_Label.setText(_translate("MainWindow", "已有交互"))
        self.interaction_delete.setText(_translate("MainWindow", "删除"))
        self.annotation.setItemText(self.annotation.indexOf(self.interaction), _translate("MainWindow", "人人交互及其原因"))
