from PyQt5 import QtCore, QtWidgets
from PyQt5.QtGui import QIcon

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(515, 510)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label1 = QtWidgets.QLabel(Form)
        self.label1.setText("")
        self.label1.setObjectName("label1")
        self.verticalLayout.addWidget(self.label1)
        self.pic1 = QtWidgets.QLabel(Form)
        self.pic1.setText("")
        self.pic1.setObjectName("pic1")
        self.verticalLayout.addWidget(self.pic1)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 10)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label2 = QtWidgets.QLabel(Form)
        self.label2.setText("")
        self.label2.setObjectName("label2")
        self.verticalLayout_2.addWidget(self.label2)
        self.pic2 = QtWidgets.QLabel(Form)
        self.pic2.setText("")
        self.pic2.setObjectName("pic2")
        self.verticalLayout_2.addWidget(self.pic2)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 10)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label3 = QtWidgets.QLabel(Form)
        self.label3.setText("")
        self.label3.setObjectName("label3")
        self.verticalLayout_3.addWidget(self.label3)
        self.pic3 = QtWidgets.QLabel(Form)
        self.pic3.setText("")
        self.pic3.setObjectName("pic3")
        self.verticalLayout_3.addWidget(self.pic3)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 10)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label4 = QtWidgets.QLabel(Form)
        self.label4.setText("")
        self.label4.setObjectName("label4")
        self.verticalLayout_4.addWidget(self.label4)
        self.pic4 = QtWidgets.QLabel(Form)
        self.pic4.setText("")
        self.pic4.setObjectName("pic4")
        self.verticalLayout_4.addWidget(self.pic4)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 10)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label5 = QtWidgets.QLabel(Form)
        self.label5.setText("")
        self.label5.setObjectName("label5")
        self.verticalLayout_5.addWidget(self.label5)
        self.pic5 = QtWidgets.QLabel(Form)
        self.pic5.setText("")
        self.pic5.setObjectName("pic5")
        self.verticalLayout_5.addWidget(self.pic5)
        self.verticalLayout_5.setStretch(0, 1)
        self.verticalLayout_5.setStretch(1, 10)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_list = QtWidgets.QComboBox(Form)
        self.label_list.setObjectName("label_list")
        self.verticalLayout_6.addWidget(self.label_list)
        self.pic_list = QtWidgets.QLabel(Form)
        self.pic_list.setText("")
        self.pic_list.setObjectName("pic_list")
        self.verticalLayout_6.addWidget(self.pic_list)
        self.delete_button = QtWidgets.QPushButton(Form)
        self.delete_button.setObjectName("delete_button")
        self.verticalLayout_6.addWidget(self.delete_button)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Example"))
        Form.setWindowIcon(QIcon('pic/face.png'))
        self.delete_button.setText(_translate("Form", "删除"))
